# This is the configuration file for the Eureka++ framework.
task: 'CartPole'
env: 'cartpole'
iteration: 4
sample: 2

# LLM Agents parameters
# The coder agent is used to generate code based on the feedback from the feedback agent.
models:
  coder_agent: 'gemma3:4b'
  coder_config:
    temperature: 0.3
    suffix: 'gemma'
  feedback_agent: 'gemma3:4b'
  feedback_config:
    temperature: 0.3
  scorer_batch_size: 8

rl:
  train_type: 'PPO'
  training_steps: 100000
  episode_length: 500
  save_model: true
  save_path: './models'
  seed: 21
  trajectory_dir: './trajectories'
  testing_episodes: 1
  render: true




